name: demo with parameter

on:
  push: 
    branches: [ main ]

jobs:
  echo-parameter:
    runs-on: ubuntu-latest
    steps:
    - name: step one
      id: step-1
      run: echo "::set-output name=my_field::My Value Is 42"
    - name: step one
      id: step-1-new
      run: echo "my_field=My Value Is 42" >> $GITHUB_OUTPUT
    - name: step two
      run: echo "my out value is ${{ steps.step-1.outputs.my_field }}"
    - name: step two new
      run: echo "my out value is ${{ steps.step-1-new.outputs.my_field }}"
      
