apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: busybox:1.28
              name: app
              command: ["sh", "-c", "echo The app is running! && sleep 45 && echo The work is done!"]
          restartPolicy: OnFailure

  