apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-app.fullname" . }}-dep
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
   matchLabels:
      {{- include "metrics-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metrics-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http1
              containerPort: 5001
              protocol: TCP
            - name: http2
              containerPort: 5001
              protocol: TCP
