apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracing-app.fullname" . }}-payment
  labels:
    {{- include "tracing-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tracing-app.selectorLabels" . | nindent 4 }}
    app: payment
