apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracing-app.fullname" . }}-ui-dep
  labels:
    {{- include "tracing-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
   matchLabels:
      {{- include "tracing-app.selectorLabels" . | nindent 6 }}
      app: ui
  template:
    metadata:
      labels:
        {{- include "tracing-app.selectorLabels" . | nindent 8 }}
        app: ui
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.ui.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.ui.pullPolicy }}
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          volumeMounts:
            - name: cfg
              mountPath: /app/appsettings.Production.json
              subPath: ui.appsettings.json
      volumes:
        - name: cfg
          configMap:
            name: {{ include "tracing-app.fullname" . }}-cm