apiVersion: v1
kind: Pod
metadata:  
  name: pod-with-vol
spec:
  containers:
    - image: fpommerening/container-training:webapp-v1
      name: app
      volumeMounts:
        - name: cfgvol
          mountPath: "/usr/share/nginx/html/test.html"
          subPath: index.html
  volumes:
    - name: cfgvol
      configMap:
        name: cfgvol