apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: data
      mountPath: "/usr/share/nginx/html/test"
  - name: sidecar
    image: busybox:1.28
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: "/home"
  volumes:
  - name: data
    emptyDir:
      medium: Memory

  
