replicaCount: 1

image:
  repository: ghcr.io/fpommerening/monitoring-for-devops
  pullPolicy: IfNotPresent
  tag: "metrics"

service:
  type: ClusterIP
  port: 8080

ingress:
  host: metrics-app.demo-apps.de
  entryPoint: web

  
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
